server:
  port: 9999

spring:
  datasource:
    username: maerdlina
    password: pass_h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/Metadata


search:
  scan-path: "C:/Users/maerd/Documents/Search/"




  #    postgres1:
#      username: maerdlina
#      password: pass_postgres_1
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5000/postgres
#    postgres2:
#      username: maerdlina
#      password: pass_postgres_2
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5001/postgres